### PR TITLE
Add support for GOPROXY env var

### PR DESCRIPTION
**Pull request by icholy**
Fixes: #35

### CODE REVIEW

**Comment by sanyatuning** [comment]
Hi!
Thank you for the fast response!
Sadly it is not working yet.
I got errors like this
```
github.com/DATA-DOG/go-sqlmock: failed: proxy: 404 Not Found
```
I debugged it a little and found the proxy server does respond with an empty body on 404 errors.
So [this line](https://github.com/icholy/gomajor/blob/af1fcfa072fb0a1d5196a6a949dc5fc4ed1438db/internal/modproxy/modproxy.go#L181) cases the problem, without body check it is working, at least for my test case.

Note: (just FYI) this env may have multiple URL-s like `GOPROXY=https://corp.example.com,https://proxy.golang.org` - [docs](https://go.dev/ref/mod#goproxy-protocol:~:text=https%3A//corp.example.com%2Chttps%3A//proxy.golang.org)
We only use one so I am happy with your solution.

**Comment by icholy** [comment]
@sanyatuning I think it should work now

**Comment by icholy** [comment]
I've tested against https://goproxy.cn and it's working.

**Comment by icholy** [comment]
Tagged as v0.13.0

**Pull request merged**
